name: .NET Build

on:
  push:
    branches: [ master, classic_era, actions ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: |
            sudo apt-get install jq curl -y

      - name: LuaObfuscator on 'private_r37p8j war2'
        shell: bash {0}
        run: |
            mkdir public
            curl -X POST https://luaobfuscator.com/api/obfuscator/newscript \
            -H "Content-type: multipart/form-data" \
            -H "apikey: test" \
            -F rotations/private_r37p8j/warrior.lua=@rotations/private_r37p8j/warrior.lua \
            | curl -X POST https://luaobfuscator.com/api/obfuscator/obfuscate \
            -H "Content-type: application/json" \
            -H "apikey: test" \
            --data "{\"MinifiyAll\":true,\"Multifile\":true,\"CustomPlugins\":{\"SwizzleLookups\":[100],\"EncryptFuncDeclaration\":[100],\"ControlFlowFlattenV1AllBlocks\":[100],\"JunkifyAllIfStatements\":[100]}}" \
            -H "sessionId: $(grep -o -P '(?<="sessionId":").*(?="})')" \
            | jq -r ".code" \
            > rotations/private_r37p8j/warrior.lua

      - name: Create artifact
        uses: actions/upload-artifact@v1
        with:
          name: Release_AddOn
          path: public/